#ifndef _EXTI_CONFIG_H
#define _EXTI_CONFIG_H

/*
 * Interrupt mask enable
 */
#define EXTI_INT_18 	DISABLE
#define EXTI_INT_17 	DISABLE
#define EXTI_INT_16 	DISABLE
#define EXTI_INT_15 	DISABLE
#define EXTI_INT_14 	DISABLE
#define EXTI_INT_13 	DISABLE
#define EXTI_INT_12 	DISABLE
#define EXTI_INT_11 	DISABLE
#define EXTI_INT_10 	DISABLE
#define EXTI_INT_9 		DISABLE
#define EXTI_INT_8 		DISABLE
#define EXTI_INT_7 		DISABLE
#define EXTI_INT_6 		DISABLE
#define EXTI_INT_5 		DISABLE
#define EXTI_INT_4 		DISABLE
#define EXTI_INT_3 		DISABLE
#define EXTI_INT_2 		DISABLE
#define EXTI_INT_1 		DISABLE
#define EXTI_INT_0 		ENABLE

/*
 * Event mask enable
 */
#define EXTI_EVENT_18 	DISABLE
#define EXTI_EVENT_17 	DISABLE
#define EXTI_EVENT_16 	DISABLE
#define EXTI_EVENT_15 	DISABLE
#define EXTI_EVENT_14 	DISABLE
#define EXTI_EVENT_13 	DISABLE
#define EXTI_EVENT_12 	DISABLE
#define EXTI_EVENT_11 	DISABLE
#define EXTI_EVENT_10 	DISABLE
#define EXTI_EVENT_9 	DISABLE
#define EXTI_EVENT_8 	DISABLE
#define EXTI_EVENT_7 	DISABLE
#define EXTI_EVENT_6 	DISABLE
#define EXTI_EVENT_5 	DISABLE
#define EXTI_EVENT_4 	DISABLE
#define EXTI_EVENT_3 	DISABLE
#define EXTI_EVENT_2 	DISABLE
#define EXTI_EVENT_1 	DISABLE
#define EXTI_EVENT_0 	DISABLE

/*
 *	Rising edge detection
 */
#define EXTI_RISING_18 	DISABLE
#define EXTI_RISING_17 	DISABLE
#define EXTI_RISING_16 	DISABLE
#define EXTI_RISING_15 	DISABLE
#define EXTI_RISING_14 	DISABLE
#define EXTI_RISING_13 	DISABLE
#define EXTI_RISING_12 	DISABLE
#define EXTI_RISING_11 	DISABLE
#define EXTI_RISING_10 	DISABLE
#define EXTI_RISING_9 	DISABLE
#define EXTI_RISING_8 	DISABLE
#define EXTI_RISING_7 	DISABLE
#define EXTI_RISING_6 	DISABLE
#define EXTI_RISING_5 	DISABLE
#define EXTI_RISING_4 	DISABLE
#define EXTI_RISING_3 	DISABLE
#define EXTI_RISING_2 	DISABLE
#define EXTI_RISING_1 	DISABLE
#define EXTI_RISING_0 	ENABLE

/*
 *	Falling edge detection
 */
#define EXTI_FALLING_18 	DISABLE
#define EXTI_FALLING_17 	DISABLE
#define EXTI_FALLING_16 	DISABLE
#define EXTI_FALLING_15 	DISABLE
#define EXTI_FALLING_14 	DISABLE
#define EXTI_FALLING_13 	DISABLE
#define EXTI_FALLING_12 	DISABLE
#define EXTI_FALLING_11 	DISABLE
#define EXTI_FALLING_10 	DISABLE
#define EXTI_FALLING_9 		DISABLE
#define EXTI_FALLING_8 		DISABLE
#define EXTI_FALLING_7 		DISABLE
#define EXTI_FALLING_6 		DISABLE
#define EXTI_FALLING_5 		DISABLE
#define EXTI_FALLING_4 		DISABLE
#define EXTI_FALLING_3 		DISABLE
#define EXTI_FALLING_2 		DISABLE
#define EXTI_FALLING_1 		DISABLE
#define EXTI_FALLING_0 		DISABLE

#endif
